apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-database-init
  namespace: investment-fund
data:
  init.sql: |
    USE authentication;

    CREATE TABLE IF NOT EXISTS user (
      id INT AUTO_INCREMENT PRIMARY KEY,
      forename VARCHAR(256) NOT NULL,
      surname VARCHAR(256) NOT NULL,
      email VARCHAR(256) NOT NULL UNIQUE,
      password VARCHAR(256) NOT NULL,
      role VARCHAR(20) NOT NULL DEFAULT 'employee'
    );

    INSERT IGNORE INTO user (
      forename,
      surname,
      email,
      password,
      role
    )
    VALUES (
      'Scrooge',
      'McDuck',
      'onlymoney@gmail.com',
      'scrypt:32768:8:1$GDf5ocY7iHiK8Idy$54388a7fe41735ad714fa5b2b75446d13214eaeaa967febedca208d0f070f27958c564f136b3af383b866206574c6032e3810978605cb1cff39189420b387aa4',
      'director'
    );

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-database-pvc
  namespace: investment-fund
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-database
  namespace: investment-fund
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-database
  template:
    metadata:
      labels:
        app: authentication-database
    spec:
      containers:
        - name: authentication-database
          image: mysql:8.4
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: investment-fund-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: investment-fund-config
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: investment-fund-config
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: investment-fund-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - name: authentication-database-storage
              mountPath: /var/lib/mysql
            - name: authentication-database-init
              mountPath: /docker-entrypoint-initdb.d

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  mysqladmin ping
                  -h 127.0.0.1
                  -u root
                  -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  mysqladmin ping
                  -h 127.0.0.1
                  -u root
                  -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

      volumes:
        - name: authentication-database-storage
          persistentVolumeClaim:
            claimName: authentication-database-pvc
        - name: authentication-database-init
          configMap:
            name: authentication-database-init


---
apiVersion: v1
kind: Service
metadata:
  name: authentication-database
  namespace: investment-fund
spec:
  selector:
    app: authentication-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP