apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-database-pvc
  namespace: investment-fund
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-database
  namespace: investment-fund
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-database
  template:
    metadata:
      labels:
        app: authentication-database
    spec:
      containers:
        - name: authentication-database
          image: mysql:8.4
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: investment-fund-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: investment-fund-config
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: investment-fund-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: investment-fund-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - name: authentication-database-storage
              mountPath: /var/lib/mysql

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  mysqladmin ping
                  -h 127.0.0.1
                  -u root
                  -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  mysqladmin ping
                  -h 127.0.0.1
                  -u root
                  -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

      volumes:
        - name: authentication-database-storage
          persistentVolumeClaim:
            claimName: authentication-database-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-database
  namespace: investment-fund
spec:
  selector:
    app: authentication-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP