apiVersion: v1
kind: Secret
metadata:
  name: investment-fund-secret
  namespace: investment-fund
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_PASSWORD: authentication_password
  JWT_SECRET_KEY: development-secret-key-at-least-32-characters
  DATABASE_URL: mysql+pymysql://authentication_user:authentication_password@authentication-database:3306/authentication